# Artist/album about texts for the demo catalogs (stand-ins for the
# enriched MusicBrainz descriptions). Two sentences each: the real UI
# renders them as collapsible About blocks in the album detail.
ARTIST_ABOUT = {
    # ---- local ----
    "Mason Vale": "Mason Vale is a highway-born Americana songwriter who writes about dust, diners and the long way home. Copper Sky was tracked live in a desert chapel with a ribbon mic on everything.",
    "Ruby Comet": "Ruby Comet is a funk outfit built on slap bass, horn stabs and hand-wired effects. Electric Honey was tracked in two takes with the whole band in one room.",
    "Spectrum": "Spectrum maps electronic journeys from ambient drift to peak-time pulse across one continuous arc. Their live set runs hardware sequencers with no laptop in sight.",
    "Luma District": "Luma District shapes dense electronic music from modular sketches and city ambience. Vector Heart maps a night walk through neon districts, block by block.",
    "Chill Vibes": "Chill Vibes bottles golden-hour calm: soft drums, warm keys and ocean air in every bar. Their sessions are mixed at low volume, exactly as intended.",
    "Vinyl Cafe": "Vinyl Cafe pours lo-fi evenings for rain on windows and coffee going cold. Every track is cut from dusty samples and a well-loved turntable.",
    "Static Orbit": "Static Orbit transmits sparse IDM signals from a bedroom studio full of blinking racks. Each piece starts as a single loop and grows by subtraction.",
    "Afterglow System": "Afterglow System rides downtempo waves between dub space and synth haze. Their records are built for the last train home.",
    "Summer on the Block": "Summer on the Block throws feel-good old school rap cookouts with live drums and park-jam energy. Every chorus is written for the whole street to shout back.",
    "Concrete Summer": "Concrete Summer picks sunlit street rap with horns, handclaps and stoop harmonies. Their selection is pure July, pressed to wax.",
    "Pop Mirage": "Pop Mirage serves sunset dance anthems with poolside synths and radio-ready hooks. Every song arrives with the top down.",
    "Modern Legends": "Modern Legends carries the hip hop essentials forward: hard drums, soul loops and bars with weight. The same crew appears in the local shelf and on TIDAL with different sessions.",
    "Static Parade": "Static Parade makes bright, hooky pop with dayglo synths and giant choruses. Color Radio is built for open windows and full-volume car stereos.",
    "Jazz Evenings": "Jazz Evenings keeps smooth sounds for quiet nights: brushed drums, muted trumpet, low light. Their records never raise their voice and never need to.",
    "Nature": "Nature records the sounds of our planet as slow ambient pieces for piano, tape and field microphones. Each album follows one landscape from dawn to dusk.",
    "Blue Meridian": "Blue Meridian is a jazz trio that plays unhurried, rain-washed standards and originals. After the Rain captures one late set where the band let every tune breathe.",
    "Neon Tides": "Neon Tides floods melodic house with salt air and strobe light in equal measure. Their EPs are mixed for big rooms and open skies.",
    "Digital Bloom": "Digital Bloom grows future garage from chopped voices and sub-bass pressure. Every track blooms late and hits all at once.",
    # ---- SMB-1 ----
    "Nova Static": "Nova Static builds neon-lit synthwave from analog arpeggios and night-drive drum machines. Midnight Relay was recorded in one long session under a ceiling of blinking sequencer lights.",
    "Saffron Tide": "Saffron Tide plays sun-bleached indie rock with room-sized guitars and close harmonies. Golden Static was cut live at golden hour on a beach-house porch.",
    "The Velvet Arcade": "The Velvet Arcade pairs bright synthpop hooks with restless sequencers and confetti-tight drums. Neon Weekend is a love letter to arcades, cassettes and staying out too late.",
    "Vector Isles": "Vector Isles builds precise electronic music from interlocking arpeggios and grid-locked drums. Pulse Theory was assembled from a single afternoon of modular jams.",
    "Static Coast": "Static Coast runs a hand-built rig of tape echoes and modular voices. Modular Hearts is four long takes with the patch cables left in place.",
    "The Alder Quartet": "The Alder Quartet is a working jazz combo with decades of club dates behind it. Midnight Session captures their last set of the night: brushed drums and unhurried piano.",
    "Iris Vale Trio": "Iris Vale Trio plays intimate jazz with a warm, close-miked upright bass. Copper Moon documents one long evening at a neighborhood residency.",
    "June Meridian": "June Meridian sings velvet-voiced vocal jazz with smoky phrasing and midnight romance. Smoke & Satin was arranged around a single candlelit piano.",
    "Velvet Brass Union": "Velvet Brass Union blends jazz with brass-band swagger and late-night soul. After Hours Mosaic stitches three club sets into one seamless evening.",
    "Harbor Swing": "Harbor Swing keeps the swing tradition alive with driving rhythm and dancing horns. Blue Avenue is a love letter to neon signs, slow dances and empty streets.",
    "Nocturne Harbor": "Nocturne Harbor writes ambient nocturnes from piano, tape and ocean sound. Golden Tides follows the tide from dusk to a glowing horizon.",
    "Aural Vector": "Aural Vector fuses modular synthesis with film-score drama. Prism Engine runs a full analog rig without a laptop in sight.",
    "Voices": "Voices gathers women in music across soul, jazz and folk into one strong choir of a record. Every song centers a voice the radio missed.",
    "Street Poet": "Street Poet deals golden age hip-hop in truth, rhythm and voice over dusty loops. The booth stays open late and the notebook never closes.",
    "Subway Saints": "Subway Saints preach raw beats and rhymes from the platform up. Their sessions smell of brake dust and sound like rush hour.",
    "Chill House": "Chill House lays beats for brighter days: soft four-on-the-floor under honeyed chords. Their mixes start at sunrise and never hurry.",
    # ---- SMB-2 ----
    "Neon Vale": "Neon Vale explores the seam between IDM and synthwave, pairing crisp machine rhythms with weightless pads. Drift Circuit is a nocturnal drive soundtrack.",
    "Circuit Dreams": "Circuit Dreams rides a synthwave odyssey on chrome arpeggios and VHS glow. Every track fades in like a memory and lands like a chase scene.",
    "Night Protocol": "Night Protocol drives darkwave after midnight: cold basslines, gated drums, fog. Headlights on, mirrors down.",
    "Prism Engine": "Prism Engine pushes progressive trance in ascend, flow and color. Their builds are patient and their drops are earned.",
    "Sunset Lowrider": "Sunset Lowrider cruises west coast 90s rap: glide bass, whistle synths, bounce. Ride low, play loud.",
    "Concrete Crown": "Concrete Crown claims legendary rap moods with power, pride and pulse. Heavy is the head, heavier is the 808.",
    "Empire Echoes": "Empire Echoes bottles east coast rap moods: night smoke and verses over crate-dug loops. Skyline views with the volume up.",
    "Cipher District": "Cipher District holds raw basement sessions where the mic passes hand to hand. Bars under pressure, no hooks wasted.",
    "Tape Royalty": "Tape Royalty rewinds mixtape classics with hiss and gold still on them. Rewind the year, keep the crown.",
    "Blue Note Alley": "Blue Note Alley deals soulful rap after dark where jazz, dust and rhyme meet. One lamp, one crate, one mic.",
    "Neon Hearts": "Neon Hearts plays retro pop nights in glow, dance and romance. Chrome hearts that never cool down.",
    "Late Afternoon Grooves": "Late Afternoon Grooves settles into jazz, soul and lounge as the light goes gold. The record shelf is deep and the chair is leather.",
    # ---- TIDAL ----
    "The Marlowe Ensemble": "The Marlowe Ensemble is a modern jazz collective with lush arrangements and long improvisations. Velvet Skyline paints the city at dusk in brushed cymbals and low brass.",
    "Blue Note": "Blue Note compiles jazz classics the way a good DJ closes the night: standards first, fireworks later. Every cut earned its place over decades of dance floors.",
    "Neon Pulse": "Neon Pulse soundtracks synthwave nights with overdrive hearts and neon circuitry. Their records play at one speed: after midnight.",
    "Midnight Drive": "Midnight Drive scores electronic afterdark hours with long headlights of synth. The city looks better at 3 AM through their windshield.",
    "Pulse Array": "Pulse Array sequences techno with laboratory patience and warehouse payoff. Every pattern locks, every break releases.",
    "Midnight Cipher": "Midnight Cipher hosts underground rap sessions where the beat never blinks. Ciphers, not singles.",
    "Golden Tape": "Golden Tape rewinds the mixtape era: hiss, bass and glory. Dubbed twice, loved forever.",
    "Rooftop Rhymes": "Rooftop Rhymes collects 90s hip-hop essentials with skyline views. Antennas up, drums out.",
    "After Hours Player": "After Hours Player soundtracks late 90s rap nights with leather-seat bass. The afterparty starts when this plays.",
    "Corner Lessons": "Corner Lessons teaches daytime rap anthems with the windows down. School is in session on every block.",
    "Electric Avenue": "Electric Avenue wires synth pop selection into streetlight anthems. Neon signs make the best choruses.",
    "Cassette Kisses": "Cassette Kisses seals sweet 80s pop with lipstick and tape hiss. Rewind to the good part.",
    "Velvet Satellite": "Velvet Satellite orbits midnight pop glamour in velvet and chrome. Signals from a lovelier frequency.",
    "Flashback Fever": "Flashback Fever spins a pop rewind collection with the best hooks of every decade. The fever breaks on the dance floor.",
    "Starlight Boulevard": "Starlight Boulevard reflects city pop back at the night in chrome and rain. Cruise tempo, always.",
    "Lazy Sundays": "Lazy Sundays plans a musical getaway in jazz, chill and soul. No alarms, no skips, no hurry.",
    "Late Night Grooves": "Late Night Grooves pours smooth sounds for quiet moments after midnight. Low light, high fidelity.",
    # ---- Spotify ----
    "Various Artists": "Various Artists gathers the Analog Stories sessions: songwriters, a borrowed guitar and one good microphone. Different voices, same wooden room.",
    "Acoustic Seaside": "Acoustic Seaside strums a chillout collection with salt on the strings. Bare feet, bottleneck slide, low tide.",
    "Luna": "Luna sings modern pop with moonlit hooks and daylight confidence. Every chorus lands like a text back.",
    "Late Afternoon": "Late Afternoon plays jazz for quiet moments when the day exhales. Soft brushes, softer light.",
    "Noir Dynasty": "Noir Dynasty deals after-midnight rap luxury in black cars and white gloves. Dynasties are built after dark.",
    # ---- Qobuz ----
    "Jazz Meets Soul": "Jazz Meets Soul stretches live sessions where the horns preach and the organ answers. Recorded in one room, mixed with restraint.",
    "Velvet Lowrider": "Velvet Lowrider cruises coastline rap with chrome rhymes and ocean air. Slow car, fast flow.",
    "Bronx Monarchy": "Bronx Monarchy rules classic boom bap authority with crowns and crates. Bow to the breakbeat.",
    "Laser Youth": "Laser Youth fires future pop motion in bright beams and sharp hooks. Young, loud and precisely aimed.",
    "Pixel Paradise": "Pixel Paradise dreams arcade pop in eight-bit color and endless summer. Insert coin, press start.",
    "Good Music": "Good Music collects a brighter state of mind across jazz, soul, funk and chill. Proof that the good stuff finds you.",
}

# Album-level overrides render as "About this album" instead of
# "About this artist", exactly like the real albumAboutHtml branch.
ALBUM_ABOUT = {
    "Smoke & Satin": "Smoke & Satin is built around June Meridian's own printed track list: six songs arranged for voice, piano and a three-piece horn section, recorded in one candlelit night.",
    "Tape Royalty": "Tape Royalty was dubbed from a shoebox of nineties mixtapes: two decks, one pencil for rewinding, no tracklist until now. What you hear is the order the tapes were found in.",
    "Color Radio": "Color Radio is Static Parade's loudest statement: ten pop songs recorded with every light in the studio on. The title track needed three key changes and one borrowed siren.",
}
